/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    NavigationArrow: THREE.Mesh;
  };
  materials: {
    ["Arrow_Material.002"]: THREE.MeshStandardMaterial;
  };
};

export function ArrowModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/arrow.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="NavigationArrow"
        castShadow
        receiveShadow
        geometry={nodes.NavigationArrow.geometry}
        material={materials["Arrow_Material.002"]}
        rotation={[0, Math.PI / 4, 0]}
        scale={[0.8, 1, 1]}
      />
    </group>
  );
}

useGLTF.preload("/arrow.glb");
