/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Nissan_350Z_Black_Mat_1: THREE.Mesh;
    Nissan_350Z_Car_Paint_1: THREE.Mesh;
    Nissan_350Z_Glass_1: THREE.Mesh;
    FL_Wheel_Black_Mat_0: THREE.Mesh;
    FL_Wheel_Metal_0: THREE.Mesh;
    FR_Wheel_Black_Mat_0: THREE.Mesh;
    FR_Wheel_Metal_0: THREE.Mesh;
    RL_Wheel_Black_Mat_0: THREE.Mesh;
    RL_Wheel_Metal_0: THREE.Mesh;
    RR_Wheel_Black_Mat_0: THREE.Mesh;
    RR_Wheel_Metal_0: THREE.Mesh;
  };
  materials: {
    Black_Mat: THREE.MeshStandardMaterial;
    Glass: THREE.MeshStandardMaterial;
    Metal: THREE.MeshStandardMaterial;
  };
};

export function CarModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/car.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.0045}
        >
          <group name="Nissan_350Zfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode">
              <group name="Nissan_350Z" position={[0, 121.77, -0.47]}>
                <mesh
                  name="Nissan_350Z_Black_Mat_1"
                  castShadow
                  receiveShadow
                  geometry={nodes.Nissan_350Z_Black_Mat_1.geometry}
                  material={materials.Black_Mat}
                />
                <mesh
                  name="Nissan_350Z_Car_Paint_1"
                  castShadow
                  receiveShadow
                  geometry={nodes.Nissan_350Z_Car_Paint_1.geometry}
                  material={materials.Black_Mat}
                />
                <mesh
                  name="Nissan_350Z_Glass_1"
                  castShadow
                  receiveShadow
                  geometry={nodes.Nissan_350Z_Glass_1.geometry}
                  material={materials.Glass}
                />
                <group name="FL_Wheel" position={[130.06, -65.77, 230.65]}>
                  <mesh
                    name="FL_Wheel_Black_Mat_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.FL_Wheel_Black_Mat_0.geometry}
                    material={materials.Black_Mat}
                  />
                  <mesh
                    name="FL_Wheel_Metal_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.FL_Wheel_Metal_0.geometry}
                    material={materials.Metal}
                  />
                </group>
                <mesh
                  name="FR_Wheel_Black_Mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.FR_Wheel_Black_Mat_0.geometry}
                  material={materials.Black_Mat}
                  position={[-130.06, -65.77, 230.65]}
                />
                <mesh
                  name="FR_Wheel_Metal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.FR_Wheel_Metal_0.geometry}
                  material={materials.Metal}
                  position={[-130.06, -65.77, 230.65]}
                />
                <mesh
                  name="RL_Wheel_Black_Mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.RL_Wheel_Black_Mat_0.geometry}
                  material={materials.Black_Mat}
                  position={[130.06, -65.77, -226.35]}
                />
                <mesh
                  name="RL_Wheel_Metal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.RL_Wheel_Metal_0.geometry}
                  material={materials.Metal}
                  position={[130.06, -65.77, -226.35]}
                />
                <mesh
                  name="RR_Wheel_Black_Mat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.RR_Wheel_Black_Mat_0.geometry}
                  material={materials.Black_Mat}
                  position={[-130.06, -65.77, -226.35]}
                />
                <mesh
                  name="RR_Wheel_Metal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.RR_Wheel_Metal_0.geometry}
                  material={materials.Metal}
                  position={[-130.06, -65.77, -226.35]}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/car.glb");
