/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Coupe_Body_Body_0: THREE.Mesh;
    Coupe_Body_Glass_0: THREE.Mesh;
    Coupe_Body_Optics_0: THREE.Mesh;
    Wheel_F_Wheel_0: THREE.Mesh;
    Wheel_F001_Wheel_0: THREE.Mesh;
    Wheel_F002_Wheel_0: THREE.Mesh;
    Wheel_F003_Wheel_0: THREE.Mesh;
  };
  materials: {
    Body_0: THREE.MeshStandardMaterial;
    Glass_0: THREE.MeshStandardMaterial;
    Optics_0: THREE.MeshStandardMaterial;
    Wheel_0: THREE.MeshStandardMaterial;
  };
};

export function ModelCar(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/car2.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[-6.091, 0, 1.977]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.001}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Coupe_Body_Body_0.geometry}
          material={materials.Body_0}
          position={[0, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Coupe_Body_Glass_0.geometry}
          material={materials.Glass_0}
          position={[0, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Coupe_Body_Optics_0.geometry}
          material={materials.Optics_0}
          position={[0, 0, 0]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel_F_Wheel_0.geometry}
        material={materials.Wheel_0}
        position={[-5.144, 0.298, 0.98]}
        rotation={[-Math.PI / 2, 0, 1.879]}
        scale={0.001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel_F003_Wheel_0.geometry}
        material={materials.Wheel_0}
        position={[-7.041, 0.298, 2.975]}
        rotation={[-Math.PI / 2, 0, 1.879]}
        scale={0.001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel_F001_Wheel_0.geometry}
        material={materials.Wheel_0}
        position={[-7.443, 0.298, 1.712]}
        rotation={[-Math.PI / 2, 0, 1.879]}
        scale={0.001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel_F002_Wheel_0.geometry}
        material={materials.Wheel_0}
        position={[-4.742, 0.298, 2.243]}
        rotation={[-Math.PI / 2, 0, 1.879]}
        scale={0.001}
      />
    </group>
  );
}

useGLTF.preload("/car2.glb");
