/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: saqib24 (https://sketchfab.com/saqib24)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/trafic-cone-88f2c1d9bb2a42368b8e6d7f14796e87
Title: Trafic Cone
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["Object001_Material_#29_0"]: THREE.Mesh;
  };
  materials: {
    Material_29: THREE.MeshStandardMaterial;
  };
};

export function ConeModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/trafic_cone.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene" scale={0.3}>
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="cc6db1857d3647199ffa86fb6ccbc901fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          >
            <group name="RootNode">
              <group
                name="Object001"
                position={[0, 10, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="Object001_Material_#29_0"
                  geometry={nodes["Object001_Material_#29_0"].geometry}
                  material={materials.Material_29}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/trafic_cone.glb");
