/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ameer Studio (https://sketchfab.com/uchiha.321abc)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tesla-2018-model-3-5ef9b845aaf44203b6d04e2c677e444f
Title: Tesla 2018 Model 3
*/

import * as THREE from "three";
import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";
import { Group } from "three";

type GLTFResult = GLTF & {
  nodes: {
    hub_rb_hub_rb0_0: THREE.Mesh;
    hub_lb_hub_rb0_0: THREE.Mesh;
    hub_rf_hub_rf0_0: THREE.Mesh;
    hub_rf_hub_rf1_0: THREE.Mesh;
    hub_lf_hub_rf0_0: THREE.Mesh;
    hub_lf_hub_rf1_0: THREE.Mesh;
    dvorright_dvorright0_0: THREE.Mesh;
    dvorleft_dvorright0_0: THREE.Mesh;
    movsteer_10_movsteer_101_0: THREE.Mesh;
    movsteer_10_movsteer_100_0: THREE.Mesh;
    movsteer_10_dvorright0_0: THREE.Mesh;
    chassis_chassis0_0: THREE.Mesh;
    JUST_BLACK_JUST_BLACK0_0: THREE.Mesh;
    JUST_BLACK001_JUST_BLACK0_0: THREE.Mesh;
    body_primary_0: THREE.Mesh;
    bodysills_primary001_0: THREE.Mesh;
    black_lights_black_lights0_0: THREE.Mesh;
    _satin_black_134_black_lights0_0: THREE.Mesh;
    _plastic_black_124_black_lights0_0: THREE.Mesh;
    back_chrome_light_back_chrome_light0_0: THREE.Mesh;
    pantulans_pantulans0_0: THREE.Mesh;
    rear_lights_right_rear_light_0: THREE.Mesh;
    light_breake_breaklight_l_0: THREE.Mesh;
    chrome_foglight_r_foglight_r_0: THREE.Mesh;
    chrome_foglight_l_foglight_l_0: THREE.Mesh;
    chrome_Lights_head_l_right_front_light_0: THREE.Mesh;
    chrome_Lights_head_l_left_front_light_0: THREE.Mesh;
    chrome_movsteer_101_0: THREE.Mesh;
    breake_int_breaklight_l_0: THREE.Mesh;
    aluminium_light_aluminium_light0_0: THREE.Mesh;
    tembus_red_tembus_red0_0: THREE.Mesh;
    interiorlights_light_night_0: THREE.Mesh;
    turn_indicat_l_indicator_lf_0: THREE.Mesh;
    turn_indicat_r_indicator_rf_0: THREE.Mesh;
    base_dvorright0_0: THREE.Mesh;
    hitam_dvorright0_0: THREE.Mesh;
    hitam001_dvorright0_0: THREE.Mesh;
    hitam002_hitam0_0: THREE.Mesh;
    Plastic_Plastic0_0: THREE.Mesh;
    belt_belt0_0: THREE.Mesh;
    black_black_lights0_0: THREE.Mesh;
    satin_red_satin_red0_0: THREE.Mesh;
    paint_black_dvorright0_0: THREE.Mesh;
    cahrome_movsteer_101_0: THREE.Mesh;
    suspensi_suspensi0_0: THREE.Mesh;
    suspensi_suspensi1_0: THREE.Mesh;
    chrome__movsteer_101_0: THREE.Mesh;
    chrome1_movsteer_101_0: THREE.Mesh;
    chrome2_movsteer_101_0: THREE.Mesh;
    hitam003_dvorright0_0: THREE.Mesh;
    hitam004_dvorright0_0: THREE.Mesh;
    aluminium_movsteer_101_0: THREE.Mesh;
    hitam005_Plastic0_0: THREE.Mesh;
    hitam006_black_lights0_0: THREE.Mesh;
    texture_Leather_movsteer_100_0: THREE.Mesh;
    texture_Leather001_movsteer_100_0: THREE.Mesh;
    aluminium2_aluminium20_0: THREE.Mesh;
    frunkplastic_dvorright0_0: THREE.Mesh;
    Putih_Putih0_0: THREE.Mesh;
    whiteleather_Putih0_0: THREE.Mesh;
    Putih001_Putih0_0: THREE.Mesh;
    Putih002_Putih0_0: THREE.Mesh;
    Carpet_Carpet0_0: THREE.Mesh;
    black001_Plastic0_0: THREE.Mesh;
    black002_Plastic0_0: THREE.Mesh;
    black003_black_lights0_0: THREE.Mesh;
    black004_JUST_BLACK0_0: THREE.Mesh;
    black005_black_lights0_0: THREE.Mesh;
    Carpet_Light_Carpet_Light0_0: THREE.Mesh;
    chromeBELT_movsteer_101_0: THREE.Mesh;
    suspensi2_suspensi0_0: THREE.Mesh;
    suspensi2_suspensi1_0: THREE.Mesh;
    texture_Buttons_texture_Buttons0_0: THREE.Mesh;
    LCDs_LCDs0_0: THREE.Mesh;
    Seat_Leather_white_Seat_Leather_white0_0: THREE.Mesh;
    Leather_white_Seat_Leather_white0_0: THREE.Mesh;
    mirror_inside_mirror_inside0_0: THREE.Mesh;
    glass_glass0_0: THREE.Mesh;
    glass_glass1_0: THREE.Mesh;
    black_boot_black_lights0_0: THREE.Mesh;
    boot_primary_0: THREE.Mesh;
    platnomor_JUST_BLACK0_0: THREE.Mesh;
    platnomor_platnomor1_0: THREE.Mesh;
    platnomor_hitam0_0: THREE.Mesh;
    platnomor_platnomor2_0: THREE.Mesh;
    chrome001_movsteer_101_0: THREE.Mesh;
    light_turn_rr_boot_indicator_rr_0: THREE.Mesh;
    light_turn_lr_boot_indicator_lr_0: THREE.Mesh;
    chrome_light_back_chrome_light0_0: THREE.Mesh;
    rear_lightsr_right_rear_light_0: THREE.Mesh;
    rear_lightsl_left_rear_light_0: THREE.Mesh;
    lightrevese_boot_revlight_L_0: THREE.Mesh;
    tembus_boot_ok_tembus_red0_0: THREE.Mesh;
    door_lf_JUST_BLACK0_0: THREE.Mesh;
    door_lf_texture_Buttons0_0: THREE.Mesh;
    door_lf_movsteer_101_0: THREE.Mesh;
    door_lf_movsteer_100_0: THREE.Mesh;
    door_lf_Putih0_0: THREE.Mesh;
    door_lf_Plastic0_0: THREE.Mesh;
    door_lf_aluminium20_0: THREE.Mesh;
    door_lf_dvorright0_0: THREE.Mesh;
    door_lf_door_lf0_0: THREE.Mesh;
    door_lf_door_lf5_0: THREE.Mesh;
    door_lf_glass0_0: THREE.Mesh;
    door_lf_mirror_inside0_0: THREE.Mesh;
    door_lf_primary_0: THREE.Mesh;
    door_lf_primary002_0: THREE.Mesh;
    door_lf_ok_primary_0: THREE.Mesh;
    door_lr_JUST_BLACK0_0: THREE.Mesh;
    door_lr_texture_Buttons0_0: THREE.Mesh;
    door_lr_primary004_0: THREE.Mesh;
    door_lr_movsteer_101_0: THREE.Mesh;
    door_lr_movsteer_100_0: THREE.Mesh;
    door_lr_Putih0_0: THREE.Mesh;
    door_lr_Plastic0_0: THREE.Mesh;
    door_lr_aluminium20_0: THREE.Mesh;
    door_lr_dvorright0_0: THREE.Mesh;
    door_lr_glass0_0: THREE.Mesh;
    door_lr_primary_0: THREE.Mesh;
    door_lr_primary002_0: THREE.Mesh;
    door_lr_ok_primary_0: THREE.Mesh;
    door_rf_JUST_BLACK0_0: THREE.Mesh;
    door_rf_texture_Buttons0_0: THREE.Mesh;
    door_rf_movsteer_101_0: THREE.Mesh;
    door_rf_movsteer_100_0: THREE.Mesh;
    door_rf_Putih0_0: THREE.Mesh;
    door_rf_Plastic0_0: THREE.Mesh;
    door_rf_aluminium20_0: THREE.Mesh;
    door_rf_dvorright0_0: THREE.Mesh;
    door_rf_door_lf0_0: THREE.Mesh;
    door_rf_glass0_0: THREE.Mesh;
    door_rf_mirror_inside0_0: THREE.Mesh;
    door_rf_primary_0: THREE.Mesh;
    door_rf_primary002_0: THREE.Mesh;
    door_rf_ok_primary_0: THREE.Mesh;
    door_rr_JUST_BLACK0_0: THREE.Mesh;
    door_rr_texture_Buttons0_0: THREE.Mesh;
    door_rr_movsteer_101_0: THREE.Mesh;
    door_rr_movsteer_100_0: THREE.Mesh;
    door_rr_Putih0_0: THREE.Mesh;
    door_rr_Plastic0_0: THREE.Mesh;
    door_rr_aluminium20_0: THREE.Mesh;
    door_rr_dvorright0_0: THREE.Mesh;
    door_rr_glass0_0: THREE.Mesh;
    door_rr_primary_0: THREE.Mesh;
    door_rr_primary002_0: THREE.Mesh;
    door_rr_ok_primary002_0: THREE.Mesh;
    windscreen_ok_glass0_0: THREE.Mesh;
    front_black_front_black0_0: THREE.Mesh;
    chrome002_back_chrome_light0_0: THREE.Mesh;
    foglights_r_foglight_r_0: THREE.Mesh;
    foglights_l_foglight_l_0: THREE.Mesh;
    indicator_lights_r_indicator_rf_0: THREE.Mesh;
    indicator_lights_l_indicator_lf_0: THREE.Mesh;
    tembus_depan_ok_tembus_red0_0: THREE.Mesh;
    front_bumper_ok_primary_0: THREE.Mesh;
    rear_bumper_movsteer_101_0: THREE.Mesh;
    rear_bumper_ok_primary_0: THREE.Mesh;
    light_pantulan_light_pantulan0_0: THREE.Mesh;
    tembus_belakang_tembus_red0_0: THREE.Mesh;
    bonnet_ok_primary_0: THREE.Mesh;
    chrome_bonnet_ok_movsteer_101_0: THREE.Mesh;
    wheels_wheels2_0: THREE.Mesh;
    wheels_wheels0_0: THREE.Mesh;
    wheels_wheels1_0: THREE.Mesh;
    wheels_movsteer_101_0: THREE.Mesh;
    wheels_wheels3_0: THREE.Mesh;
    wheels_wheels4_0: THREE.Mesh;
    wheels_wheels6_0: THREE.Mesh;
    wheels001_wheels2_0: THREE.Mesh;
    wheels001_wheels0_0: THREE.Mesh;
    wheels001_wheels1_0: THREE.Mesh;
    wheels001_movsteer_101_0: THREE.Mesh;
    wheels001_wheels3_0: THREE.Mesh;
    wheels001_wheels4_0: THREE.Mesh;
    wheels001_wheels6_0: THREE.Mesh;
  };
  materials: {
    ["hub_rb.0"]: THREE.MeshStandardMaterial;
    ["hub_rf.0"]: THREE.MeshStandardMaterial;
    ["hub_rf.1"]: THREE.MeshStandardMaterial;
    ["dvorright.0"]: THREE.MeshStandardMaterial;
    ["movsteer_1.0.1"]: THREE.MeshStandardMaterial;
    ["movsteer_1.0.0"]: THREE.MeshStandardMaterial;
    ["chassis.0"]: THREE.MeshStandardMaterial;
    ["JUST_BLACK.0"]: THREE.MeshStandardMaterial;
    primary: THREE.MeshStandardMaterial;
    ["primary.001"]: THREE.MeshStandardMaterial;
    ["black_lights.0"]: THREE.MeshStandardMaterial;
    ["back_chrome_light.0"]: THREE.MeshStandardMaterial;
    ["pantulans.0"]: THREE.MeshStandardMaterial;
    right_rear_light: THREE.MeshStandardMaterial;
    breaklight_l: THREE.MeshStandardMaterial;
    foglight_r: THREE.MeshStandardMaterial;
    foglight_l: THREE.MeshStandardMaterial;
    right_front_light: THREE.MeshStandardMaterial;
    left_front_light: THREE.MeshStandardMaterial;
    ["aluminium_light.0"]: THREE.MeshStandardMaterial;
    ["tembus_red.0"]: THREE.MeshStandardMaterial;
    light_night: THREE.MeshStandardMaterial;
    indicator_lf: THREE.MeshStandardMaterial;
    indicator_rf: THREE.MeshStandardMaterial;
    ["hitam.0"]: THREE.MeshStandardMaterial;
    ["Plastic.0"]: THREE.MeshStandardMaterial;
    ["belt.0"]: THREE.MeshStandardMaterial;
    ["satin_red.0"]: THREE.MeshStandardMaterial;
    ["suspensi.0"]: THREE.MeshStandardMaterial;
    ["suspensi.1"]: THREE.MeshStandardMaterial;
    ["aluminium2.0"]: THREE.MeshStandardMaterial;
    ["Putih.0"]: THREE.MeshStandardMaterial;
    ["Carpet.0"]: THREE.MeshStandardMaterial;
    ["Carpet_Light.0"]: THREE.MeshStandardMaterial;
    ["texture_Buttons.0"]: THREE.MeshStandardMaterial;
    ["LCDs.0"]: THREE.MeshStandardMaterial;
    ["Seat_Leather_white.0"]: THREE.MeshStandardMaterial;
    ["mirror_inside.0"]: THREE.MeshStandardMaterial;
    ["glass.0"]: THREE.MeshStandardMaterial;
    ["glass.1"]: THREE.MeshStandardMaterial;
    ["platnomor.1"]: THREE.MeshStandardMaterial;
    ["platnomor.2"]: THREE.MeshStandardMaterial;
    indicator_rr: THREE.MeshStandardMaterial;
    indicator_lr: THREE.MeshStandardMaterial;
    left_rear_light: THREE.MeshStandardMaterial;
    revlight_L: THREE.MeshStandardMaterial;
    ["door_lf.0"]: THREE.MeshStandardMaterial;
    ["door_lf.5"]: THREE.MeshStandardMaterial;
    ["primary.002"]: THREE.MeshStandardMaterial;
    ["primary.004"]: THREE.MeshStandardMaterial;
    ["front_black.0"]: THREE.MeshStandardMaterial;
    ["light_pantulan.0"]: THREE.MeshStandardMaterial;
    ["wheels.2"]: THREE.MeshStandardMaterial;
    ["wheels.0"]: THREE.MeshStandardMaterial;
    ["wheels.1"]: THREE.MeshStandardMaterial;
    ["wheels.3"]: THREE.MeshStandardMaterial;
    ["wheels.4"]: THREE.MeshStandardMaterial;
    ["wheels.6"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/tesla_2018_model_3.glb") as GLTFResult;

  const frontWheelsRef = useRef<Group>(null);
  const rearWheelsRef = useRef<Group>(null);

  useEffect(() => {
    let frameId: number;
    let lastTime = performance.now(); // 记录上一次帧的时间

    const rotateWheels = (currentTime: number) => {
      const deltaTime = (currentTime - lastTime) / 1000; // 计算时间差（秒）
      lastTime = currentTime;

      const rotationSpeed = 1.2; // 每秒旋转的弧度

      if (frontWheelsRef.current && rearWheelsRef.current) {
        // 使用时间差乘以速度来计算旋转
        frontWheelsRef.current.rotation.x -= rotationSpeed * deltaTime;
        rearWheelsRef.current.rotation.x -= rotationSpeed * deltaTime;
      }

      frameId = requestAnimationFrame(rotateWheels);
    };

    frameId = requestAnimationFrame(rotateWheels);

    return () => {
      cancelAnimationFrame(frameId);
    };
  }, []);

  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="888d5b4c0a7b42299d217c2edec42266fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="RootNode">
              <group
                name="Tesla_Model_3"
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              >
                <group name="hub_rb" position={[0.898, -1.447, -0.372]}>
                  <mesh
                    name="hub_rb_hub_rb0_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.hub_rb_hub_rb0_0.geometry}
                    material={materials["hub_rb.0"]}
                  />
                </group>
                <group name="hub_lb" position={[-0.898, -1.446, -0.372]}>
                  <mesh
                    name="hub_lb_hub_rb0_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.hub_lb_hub_rb0_0.geometry}
                    material={materials["hub_rb.0"]}
                  />
                </group>
                <group name="hub_rf" position={[0.924, 1.757, -0.372]}>
                  <mesh
                    name="hub_rf_hub_rf0_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.hub_rf_hub_rf0_0.geometry}
                    material={materials["hub_rf.0"]}
                  />
                  <mesh
                    name="hub_rf_hub_rf1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.hub_rf_hub_rf1_0.geometry}
                    material={materials["hub_rf.1"]}
                  />
                </group>
                <group name="hub_lf" position={[-0.925, 1.757, -0.372]}>
                  <mesh
                    name="hub_lf_hub_rf0_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.hub_lf_hub_rf0_0.geometry}
                    material={materials["hub_rf.0"]}
                  />
                  <mesh
                    name="hub_lf_hub_rf1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.hub_lf_hub_rf1_0.geometry}
                    material={materials["hub_rf.1"]}
                  />
                </group>
                <group
                  name="dvornik_dummy"
                  position={[-0.083, 1.605, 0.177]}
                  rotation={[0.956, 0, 0]}
                >
                  <group name="dvorright">
                    <mesh
                      name="dvorright_dvorright0_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.dvorright_dvorright0_0.geometry}
                      material={materials["dvorright.0"]}
                    />
                  </group>
                  <group
                    name="other"
                    position={[-0.623, -0.079, 0.171]}
                    rotation={[0.133, 0, 0]}
                  >
                    <group name="dvorleft">
                      <mesh
                        name="dvorleft_dvorright0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.dvorleft_dvorright0_0.geometry}
                        material={materials["dvorright.0"]}
                      />
                    </group>
                  </group>
                </group>
                <group
                  name="steering_dummy"
                  position={[-0.47, 0.608, 0.176]}
                  rotation={[-0.308, 0, 0]}
                >
                  <group name="movsteer_10">
                    <mesh
                      name="movsteer_10_movsteer_101_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.movsteer_10_movsteer_101_0.geometry}
                      material={materials["movsteer_1.0.1"]}
                    />
                    <mesh
                      name="movsteer_10_movsteer_100_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.movsteer_10_movsteer_100_0.geometry}
                      material={materials["movsteer_1.0.0"]}
                    />
                    <mesh
                      name="movsteer_10_dvorright0_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.movsteer_10_dvorright0_0.geometry}
                      material={materials["dvorright.0"]}
                    />
                  </group>
                </group>
                <group name="chassis_dummy">
                  <group name="chassis" position={[0, 1.771, -0.362]}>
                    <mesh
                      name="chassis_chassis0_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.chassis_chassis0_0.geometry}
                      material={materials["chassis.0"]}
                    />
                    <group name="JUST_BLACK" position={[0, -1.771, 0.362]}>
                      <mesh
                        name="JUST_BLACK_JUST_BLACK0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.JUST_BLACK_JUST_BLACK0_0.geometry}
                        material={materials["JUST_BLACK.0"]}
                      />
                      <group name="JUST_BLACK001">
                        <mesh
                          name="JUST_BLACK001_JUST_BLACK0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.JUST_BLACK001_JUST_BLACK0_0.geometry}
                          material={materials["JUST_BLACK.0"]}
                        />
                      </group>
                    </group>
                    <group name="body" position={[0, -1.771, 0.362]}>
                      <mesh
                        name="body_primary_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.body_primary_0.geometry}
                        material={materials.primary}
                      />
                    </group>
                    <group name="bodysills" position={[0, -1.771, 0.362]}>
                      <mesh
                        name="bodysills_primary001_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.bodysills_primary001_0.geometry}
                        material={materials["primary.001"]}
                      />
                    </group>
                    <group name="black_lights" position={[0, -1.771, 0.362]}>
                      <mesh
                        name="black_lights_black_lights0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.black_lights_black_lights0_0.geometry}
                        material={materials["black_lights.0"]}
                      />
                      <group name="_satin_black_134">
                        <mesh
                          name="_satin_black_134_black_lights0_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes._satin_black_134_black_lights0_0.geometry
                          }
                          material={materials["black_lights.0"]}
                        />
                        <group name="_plastic_black_124">
                          <mesh
                            name="_plastic_black_124_black_lights0_0"
                            castShadow
                            receiveShadow
                            geometry={
                              nodes._plastic_black_124_black_lights0_0.geometry
                            }
                            material={materials["black_lights.0"]}
                          />
                        </group>
                      </group>
                      <group name="back_chrome_light">
                        <mesh
                          name="back_chrome_light_back_chrome_light0_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.back_chrome_light_back_chrome_light0_0
                              .geometry
                          }
                          material={materials["back_chrome_light.0"]}
                        />
                        <group name="pantulans">
                          <mesh
                            name="pantulans_pantulans0_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.pantulans_pantulans0_0.geometry}
                            material={materials["pantulans.0"]}
                          />
                        </group>
                        <group name="rear_lights">
                          <mesh
                            name="rear_lights_right_rear_light_0"
                            castShadow
                            receiveShadow
                            geometry={
                              nodes.rear_lights_right_rear_light_0.geometry
                            }
                            material={materials.right_rear_light}
                          />
                        </group>
                        <group name="light_breake">
                          <mesh
                            name="light_breake_breaklight_l_0"
                            castShadow
                            receiveShadow
                            geometry={
                              nodes.light_breake_breaklight_l_0.geometry
                            }
                            material={materials.breaklight_l}
                          />
                        </group>
                      </group>
                      <group name="chrome_foglight_r">
                        <mesh
                          name="chrome_foglight_r_foglight_r_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.chrome_foglight_r_foglight_r_0.geometry
                          }
                          material={materials.foglight_r}
                        />
                      </group>
                      <group name="chrome_foglight_l">
                        <mesh
                          name="chrome_foglight_l_foglight_l_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.chrome_foglight_l_foglight_l_0.geometry
                          }
                          material={materials.foglight_l}
                        />
                      </group>
                      <group name="chrome_Lights_head_l">
                        <mesh
                          name="chrome_Lights_head_l_right_front_light_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.chrome_Lights_head_l_right_front_light_0
                              .geometry
                          }
                          material={materials.right_front_light}
                        />
                        <mesh
                          name="chrome_Lights_head_l_left_front_light_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.chrome_Lights_head_l_left_front_light_0
                              .geometry
                          }
                          material={materials.left_front_light}
                        />
                      </group>
                      <group name="chrome">
                        <mesh
                          name="chrome_movsteer_101_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.chrome_movsteer_101_0.geometry}
                          material={materials["movsteer_1.0.1"]}
                        />
                      </group>
                      <group name="breake_int">
                        <mesh
                          name="breake_int_breaklight_l_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.breake_int_breaklight_l_0.geometry}
                          material={materials.breaklight_l}
                        />
                      </group>
                      <group name="aluminium_light">
                        <mesh
                          name="aluminium_light_aluminium_light0_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.aluminium_light_aluminium_light0_0.geometry
                          }
                          material={materials["aluminium_light.0"]}
                        />
                      </group>
                      <group name="tembus_red">
                        <mesh
                          name="tembus_red_tembus_red0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.tembus_red_tembus_red0_0.geometry}
                          material={materials["tembus_red.0"]}
                        />
                      </group>
                      <group name="interiorlights">
                        <mesh
                          name="interiorlights_light_night_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.interiorlights_light_night_0.geometry}
                          material={materials.light_night}
                        />
                      </group>
                      <group name="turn_indicat_l" position={[0.002, 0, 0]}>
                        <mesh
                          name="turn_indicat_l_indicator_lf_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.turn_indicat_l_indicator_lf_0.geometry
                          }
                          material={materials.indicator_lf}
                        />
                      </group>
                      <group name="turn_indicat_r" position={[0.002, 0, 0]}>
                        <mesh
                          name="turn_indicat_r_indicator_rf_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.turn_indicat_r_indicator_rf_0.geometry
                          }
                          material={materials.indicator_rf}
                        />
                      </group>
                    </group>
                    <group name="base" position={[0, -1.771, 0.362]}>
                      <mesh
                        name="base_dvorright0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.base_dvorright0_0.geometry}
                        material={materials["dvorright.0"]}
                      />
                      <group name="hitam">
                        <mesh
                          name="hitam_dvorright0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.hitam_dvorright0_0.geometry}
                          material={materials["dvorright.0"]}
                        />
                      </group>
                      <group name="hitam001">
                        <mesh
                          name="hitam001_dvorright0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.hitam001_dvorright0_0.geometry}
                          material={materials["dvorright.0"]}
                        />
                      </group>
                      <group name="hitam002">
                        <mesh
                          name="hitam002_hitam0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.hitam002_hitam0_0.geometry}
                          material={materials["hitam.0"]}
                        />
                      </group>
                      <group name="Plastic">
                        <mesh
                          name="Plastic_Plastic0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Plastic_Plastic0_0.geometry}
                          material={materials["Plastic.0"]}
                        />
                      </group>
                      <group name="belt">
                        <mesh
                          name="belt_belt0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.belt_belt0_0.geometry}
                          material={materials["belt.0"]}
                        />
                      </group>
                      <group name="black">
                        <mesh
                          name="black_black_lights0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.black_black_lights0_0.geometry}
                          material={materials["black_lights.0"]}
                        />
                      </group>
                      <group name="satin_red">
                        <mesh
                          name="satin_red_satin_red0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.satin_red_satin_red0_0.geometry}
                          material={materials["satin_red.0"]}
                        />
                      </group>
                      <group name="paint_black">
                        <mesh
                          name="paint_black_dvorright0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.paint_black_dvorright0_0.geometry}
                          material={materials["dvorright.0"]}
                        />
                      </group>
                      <group name="cahrome">
                        <mesh
                          name="cahrome_movsteer_101_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.cahrome_movsteer_101_0.geometry}
                          material={materials["movsteer_1.0.1"]}
                        />
                      </group>
                      <group name="suspensi">
                        <mesh
                          name="suspensi_suspensi0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.suspensi_suspensi0_0.geometry}
                          material={materials["suspensi.0"]}
                        />
                        <mesh
                          name="suspensi_suspensi1_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.suspensi_suspensi1_0.geometry}
                          material={materials["suspensi.1"]}
                        />
                      </group>
                      <group name="chrome_">
                        <mesh
                          name="chrome__movsteer_101_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.chrome__movsteer_101_0.geometry}
                          material={materials["movsteer_1.0.1"]}
                        />
                      </group>
                      <group name="chrome1">
                        <mesh
                          name="chrome1_movsteer_101_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.chrome1_movsteer_101_0.geometry}
                          material={materials["movsteer_1.0.1"]}
                        />
                      </group>
                      <group name="chrome2">
                        <mesh
                          name="chrome2_movsteer_101_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.chrome2_movsteer_101_0.geometry}
                          material={materials["movsteer_1.0.1"]}
                        />
                      </group>
                      <group name="hitam003">
                        <mesh
                          name="hitam003_dvorright0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.hitam003_dvorright0_0.geometry}
                          material={materials["dvorright.0"]}
                        />
                      </group>
                      <group name="hitam004">
                        <mesh
                          name="hitam004_dvorright0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.hitam004_dvorright0_0.geometry}
                          material={materials["dvorright.0"]}
                        />
                      </group>
                      <group name="aluminium">
                        <mesh
                          name="aluminium_movsteer_101_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.aluminium_movsteer_101_0.geometry}
                          material={materials["movsteer_1.0.1"]}
                        />
                      </group>
                      <group name="hitam005">
                        <mesh
                          name="hitam005_Plastic0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.hitam005_Plastic0_0.geometry}
                          material={materials["Plastic.0"]}
                        />
                      </group>
                      <group name="hitam006">
                        <mesh
                          name="hitam006_black_lights0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.hitam006_black_lights0_0.geometry}
                          material={materials["black_lights.0"]}
                        />
                      </group>
                      <group name="texture_Leather">
                        <mesh
                          name="texture_Leather_movsteer_100_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.texture_Leather_movsteer_100_0.geometry
                          }
                          material={materials["movsteer_1.0.0"]}
                        />
                      </group>
                      <group name="texture_Leather001">
                        <mesh
                          name="texture_Leather001_movsteer_100_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.texture_Leather001_movsteer_100_0.geometry
                          }
                          material={materials["movsteer_1.0.0"]}
                        />
                      </group>
                      <group name="aluminium2">
                        <mesh
                          name="aluminium2_aluminium20_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.aluminium2_aluminium20_0.geometry}
                          material={materials["aluminium2.0"]}
                        />
                      </group>
                      <group name="frunkplastic">
                        <mesh
                          name="frunkplastic_dvorright0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.frunkplastic_dvorright0_0.geometry}
                          material={materials["dvorright.0"]}
                        />
                      </group>
                      <group name="Putih">
                        <mesh
                          name="Putih_Putih0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Putih_Putih0_0.geometry}
                          material={materials["Putih.0"]}
                        />
                      </group>
                      <group name="whiteleather">
                        <mesh
                          name="whiteleather_Putih0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.whiteleather_Putih0_0.geometry}
                          material={materials["Putih.0"]}
                        />
                      </group>
                      <group name="Putih001">
                        <mesh
                          name="Putih001_Putih0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Putih001_Putih0_0.geometry}
                          material={materials["Putih.0"]}
                        />
                      </group>
                      <group name="Putih002">
                        <mesh
                          name="Putih002_Putih0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Putih002_Putih0_0.geometry}
                          material={materials["Putih.0"]}
                        />
                      </group>
                      <group name="Carpet">
                        <mesh
                          name="Carpet_Carpet0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Carpet_Carpet0_0.geometry}
                          material={materials["Carpet.0"]}
                        />
                      </group>
                      <group name="black001">
                        <mesh
                          name="black001_Plastic0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.black001_Plastic0_0.geometry}
                          material={materials["Plastic.0"]}
                        />
                      </group>
                      <group name="black002">
                        <mesh
                          name="black002_Plastic0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.black002_Plastic0_0.geometry}
                          material={materials["Plastic.0"]}
                        />
                      </group>
                      <group name="black003">
                        <mesh
                          name="black003_black_lights0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.black003_black_lights0_0.geometry}
                          material={materials["black_lights.0"]}
                        />
                      </group>
                      <group name="black004">
                        <mesh
                          name="black004_JUST_BLACK0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.black004_JUST_BLACK0_0.geometry}
                          material={materials["JUST_BLACK.0"]}
                        />
                      </group>
                      <group name="black005">
                        <mesh
                          name="black005_black_lights0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.black005_black_lights0_0.geometry}
                          material={materials["black_lights.0"]}
                        />
                      </group>
                      <group name="Carpet_Light">
                        <mesh
                          name="Carpet_Light_Carpet_Light0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Carpet_Light_Carpet_Light0_0.geometry}
                          material={materials["Carpet_Light.0"]}
                        />
                      </group>
                      <group name="chromeBELT">
                        <mesh
                          name="chromeBELT_movsteer_101_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.chromeBELT_movsteer_101_0.geometry}
                          material={materials["movsteer_1.0.1"]}
                        />
                      </group>
                      <group name="suspensi2">
                        <mesh
                          name="suspensi2_suspensi0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.suspensi2_suspensi0_0.geometry}
                          material={materials["suspensi.0"]}
                        />
                        <mesh
                          name="suspensi2_suspensi1_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.suspensi2_suspensi1_0.geometry}
                          material={materials["suspensi.1"]}
                        />
                      </group>
                      <group name="texture_Buttons">
                        <mesh
                          name="texture_Buttons_texture_Buttons0_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.texture_Buttons_texture_Buttons0_0.geometry
                          }
                          material={materials["texture_Buttons.0"]}
                        />
                      </group>
                      <group name="LCDs">
                        <mesh
                          name="LCDs_LCDs0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.LCDs_LCDs0_0.geometry}
                          material={materials["LCDs.0"]}
                        />
                      </group>
                      <group name="Seat_Leather_white">
                        <mesh
                          name="Seat_Leather_white_Seat_Leather_white0_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Seat_Leather_white_Seat_Leather_white0_0
                              .geometry
                          }
                          material={materials["Seat_Leather_white.0"]}
                        />
                        <group name="Leather_white">
                          <mesh
                            name="Leather_white_Seat_Leather_white0_0"
                            castShadow
                            receiveShadow
                            geometry={
                              nodes.Leather_white_Seat_Leather_white0_0.geometry
                            }
                            material={materials["Seat_Leather_white.0"]}
                          />
                        </group>
                      </group>
                      <group name="mirror_inside">
                        <mesh
                          name="mirror_inside_mirror_inside0_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.mirror_inside_mirror_inside0_0.geometry
                          }
                          material={materials["mirror_inside.0"]}
                        />
                      </group>
                    </group>
                    <group name="glass" position={[0, -1.042, 0.935]}>
                      <mesh
                        name="glass_glass0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.glass_glass0_0.geometry}
                        material={materials["glass.0"]}
                      />
                      <mesh
                        name="glass_glass1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.glass_glass1_0.geometry}
                        material={materials["glass.1"]}
                      />
                    </group>
                  </group>
                  <group name="boot_dummy" position={[0, -1.692, 0.597]}>
                    <group name="black_boot">
                      <mesh
                        name="black_boot_black_lights0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.black_boot_black_lights0_0.geometry}
                        material={materials["black_lights.0"]}
                      />
                      <group name="boot">
                        <mesh
                          name="boot_primary_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.boot_primary_0.geometry}
                          material={materials.primary}
                        />
                      </group>
                      <group name="platnomor">
                        <mesh
                          name="platnomor_JUST_BLACK0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.platnomor_JUST_BLACK0_0.geometry}
                          material={materials["JUST_BLACK.0"]}
                        />
                        <mesh
                          name="platnomor_platnomor1_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.platnomor_platnomor1_0.geometry}
                          material={materials["platnomor.1"]}
                        />
                        <mesh
                          name="platnomor_hitam0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.platnomor_hitam0_0.geometry}
                          material={materials["hitam.0"]}
                        />
                        <mesh
                          name="platnomor_platnomor2_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.platnomor_platnomor2_0.geometry}
                          material={materials["platnomor.2"]}
                        />
                      </group>
                      <group name="chrome001">
                        <mesh
                          name="chrome001_movsteer_101_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.chrome001_movsteer_101_0.geometry}
                          material={materials["movsteer_1.0.1"]}
                        />
                      </group>
                      <group name="light_turn_rr_boot">
                        <mesh
                          name="light_turn_rr_boot_indicator_rr_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.light_turn_rr_boot_indicator_rr_0.geometry
                          }
                          material={materials.indicator_rr}
                        />
                      </group>
                      <group name="light_turn_lr_boot">
                        <mesh
                          name="light_turn_lr_boot_indicator_lr_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.light_turn_lr_boot_indicator_lr_0.geometry
                          }
                          material={materials.indicator_lr}
                        />
                      </group>
                      <group name="chrome_light">
                        <mesh
                          name="chrome_light_back_chrome_light0_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.chrome_light_back_chrome_light0_0.geometry
                          }
                          material={materials["back_chrome_light.0"]}
                        />
                      </group>
                      <group name="rear_lightsr">
                        <mesh
                          name="rear_lightsr_right_rear_light_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.rear_lightsr_right_rear_light_0.geometry
                          }
                          material={materials.right_rear_light}
                        />
                      </group>
                      <group name="rear_lightsl">
                        <mesh
                          name="rear_lightsl_left_rear_light_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.rear_lightsl_left_rear_light_0.geometry
                          }
                          material={materials.left_rear_light}
                        />
                      </group>
                      <group name="lightrevese_boot">
                        <mesh
                          name="lightrevese_boot_revlight_L_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.lightrevese_boot_revlight_L_0.geometry
                          }
                          material={materials.revlight_L}
                        />
                      </group>
                      <group name="tembus_boot_ok">
                        <mesh
                          name="tembus_boot_ok_tembus_red0_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.tembus_boot_ok_tembus_red0_0.geometry}
                          material={materials["tembus_red.0"]}
                        />
                      </group>
                    </group>
                  </group>
                  <group
                    name="door_lf_dummy"
                    position={[-1.006, 1.175, -0.063]}
                  >
                    <group name="door_lf">
                      <mesh
                        name="door_lf_JUST_BLACK0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_lf_JUST_BLACK0_0.geometry}
                        material={materials["JUST_BLACK.0"]}
                      />
                      <mesh
                        name="door_lf_texture_Buttons0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_lf_texture_Buttons0_0.geometry}
                        material={materials["texture_Buttons.0"]}
                      />
                      <mesh
                        name="door_lf_movsteer_101_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_lf_movsteer_101_0.geometry}
                        material={materials["movsteer_1.0.1"]}
                      />
                      <mesh
                        name="door_lf_movsteer_100_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_lf_movsteer_100_0.geometry}
                        material={materials["movsteer_1.0.0"]}
                      />
                      <mesh
                        name="door_lf_Putih0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_lf_Putih0_0.geometry}
                        material={materials["Putih.0"]}
                      />
                      <mesh
                        name="door_lf_Plastic0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_lf_Plastic0_0.geometry}
                        material={materials["Plastic.0"]}
                      />
                      <mesh
                        name="door_lf_aluminium20_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_lf_aluminium20_0.geometry}
                        material={materials["aluminium2.0"]}
                      />
                      <mesh
                        name="door_lf_dvorright0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_lf_dvorright0_0.geometry}
                        material={materials["dvorright.0"]}
                      />
                      <mesh
                        name="door_lf_door_lf0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_lf_door_lf0_0.geometry}
                        material={materials["door_lf.0"]}
                      />
                      <mesh
                        name="door_lf_door_lf5_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_lf_door_lf5_0.geometry}
                        material={materials["door_lf.5"]}
                      />
                      <mesh
                        name="door_lf_glass0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_lf_glass0_0.geometry}
                        material={materials["glass.0"]}
                      />
                      <mesh
                        name="door_lf_mirror_inside0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_lf_mirror_inside0_0.geometry}
                        material={materials["mirror_inside.0"]}
                      />
                      <mesh
                        name="door_lf_primary_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_lf_primary_0.geometry}
                        material={materials.primary}
                      />
                      <mesh
                        name="door_lf_primary002_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_lf_primary002_0.geometry}
                        material={materials["primary.002"]}
                      />
                      <group name="door_lf_ok">
                        <mesh
                          name="door_lf_ok_primary_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.door_lf_ok_primary_0.geometry}
                          material={materials.primary}
                        />
                      </group>
                    </group>
                  </group>
                  <group
                    name="door_lr_dummy"
                    position={[-1.033, -0.131, -0.063]}
                  >
                    <group name="door_lr">
                      <mesh
                        name="door_lr_JUST_BLACK0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_lr_JUST_BLACK0_0.geometry}
                        material={materials["JUST_BLACK.0"]}
                      />
                      <mesh
                        name="door_lr_texture_Buttons0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_lr_texture_Buttons0_0.geometry}
                        material={materials["texture_Buttons.0"]}
                      />
                      <mesh
                        name="door_lr_primary004_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_lr_primary004_0.geometry}
                        material={materials["primary.004"]}
                      />
                      <mesh
                        name="door_lr_movsteer_101_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_lr_movsteer_101_0.geometry}
                        material={materials["movsteer_1.0.1"]}
                      />
                      <mesh
                        name="door_lr_movsteer_100_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_lr_movsteer_100_0.geometry}
                        material={materials["movsteer_1.0.0"]}
                      />
                      <mesh
                        name="door_lr_Putih0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_lr_Putih0_0.geometry}
                        material={materials["Putih.0"]}
                      />
                      <mesh
                        name="door_lr_Plastic0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_lr_Plastic0_0.geometry}
                        material={materials["Plastic.0"]}
                      />
                      <mesh
                        name="door_lr_aluminium20_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_lr_aluminium20_0.geometry}
                        material={materials["aluminium2.0"]}
                      />
                      <mesh
                        name="door_lr_dvorright0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_lr_dvorright0_0.geometry}
                        material={materials["dvorright.0"]}
                      />
                      <mesh
                        name="door_lr_glass0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_lr_glass0_0.geometry}
                        material={materials["glass.0"]}
                      />
                      <mesh
                        name="door_lr_primary_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_lr_primary_0.geometry}
                        material={materials.primary}
                      />
                      <mesh
                        name="door_lr_primary002_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_lr_primary002_0.geometry}
                        material={materials["primary.002"]}
                      />
                      <group name="door_lr_ok">
                        <mesh
                          name="door_lr_ok_primary_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.door_lr_ok_primary_0.geometry}
                          material={materials.primary}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="door_rf_dummy" position={[1.006, 1.175, -0.063]}>
                    <group name="door_rf">
                      <mesh
                        name="door_rf_JUST_BLACK0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_rf_JUST_BLACK0_0.geometry}
                        material={materials["JUST_BLACK.0"]}
                      />
                      <mesh
                        name="door_rf_texture_Buttons0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_rf_texture_Buttons0_0.geometry}
                        material={materials["texture_Buttons.0"]}
                      />
                      <mesh
                        name="door_rf_movsteer_101_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_rf_movsteer_101_0.geometry}
                        material={materials["movsteer_1.0.1"]}
                      />
                      <mesh
                        name="door_rf_movsteer_100_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_rf_movsteer_100_0.geometry}
                        material={materials["movsteer_1.0.0"]}
                      />
                      <mesh
                        name="door_rf_Putih0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_rf_Putih0_0.geometry}
                        material={materials["Putih.0"]}
                      />
                      <mesh
                        name="door_rf_Plastic0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_rf_Plastic0_0.geometry}
                        material={materials["Plastic.0"]}
                      />
                      <mesh
                        name="door_rf_aluminium20_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_rf_aluminium20_0.geometry}
                        material={materials["aluminium2.0"]}
                      />
                      <mesh
                        name="door_rf_dvorright0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_rf_dvorright0_0.geometry}
                        material={materials["dvorright.0"]}
                      />
                      <mesh
                        name="door_rf_door_lf0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_rf_door_lf0_0.geometry}
                        material={materials["door_lf.0"]}
                      />
                      <mesh
                        name="door_rf_glass0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_rf_glass0_0.geometry}
                        material={materials["glass.0"]}
                      />
                      <mesh
                        name="door_rf_mirror_inside0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_rf_mirror_inside0_0.geometry}
                        material={materials["mirror_inside.0"]}
                      />
                      <mesh
                        name="door_rf_primary_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_rf_primary_0.geometry}
                        material={materials.primary}
                      />
                      <mesh
                        name="door_rf_primary002_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_rf_primary002_0.geometry}
                        material={materials["primary.002"]}
                      />
                      <group name="door_rf_ok">
                        <mesh
                          name="door_rf_ok_primary_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.door_rf_ok_primary_0.geometry}
                          material={materials.primary}
                        />
                      </group>
                    </group>
                  </group>
                  <group
                    name="door_rr_dummy"
                    position={[1.033, -0.131, -0.063]}
                  >
                    <group name="door_rr">
                      <mesh
                        name="door_rr_JUST_BLACK0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_rr_JUST_BLACK0_0.geometry}
                        material={materials["JUST_BLACK.0"]}
                      />
                      <mesh
                        name="door_rr_texture_Buttons0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_rr_texture_Buttons0_0.geometry}
                        material={materials["texture_Buttons.0"]}
                      />
                      <mesh
                        name="door_rr_movsteer_101_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_rr_movsteer_101_0.geometry}
                        material={materials["movsteer_1.0.1"]}
                      />
                      <mesh
                        name="door_rr_movsteer_100_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_rr_movsteer_100_0.geometry}
                        material={materials["movsteer_1.0.0"]}
                      />
                      <mesh
                        name="door_rr_Putih0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_rr_Putih0_0.geometry}
                        material={materials["Putih.0"]}
                      />
                      <mesh
                        name="door_rr_Plastic0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_rr_Plastic0_0.geometry}
                        material={materials["Plastic.0"]}
                      />
                      <mesh
                        name="door_rr_aluminium20_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_rr_aluminium20_0.geometry}
                        material={materials["aluminium2.0"]}
                      />
                      <mesh
                        name="door_rr_dvorright0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_rr_dvorright0_0.geometry}
                        material={materials["dvorright.0"]}
                      />
                      <mesh
                        name="door_rr_glass0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_rr_glass0_0.geometry}
                        material={materials["glass.0"]}
                      />
                      <mesh
                        name="door_rr_primary_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_rr_primary_0.geometry}
                        material={materials.primary}
                      />
                      <mesh
                        name="door_rr_primary002_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.door_rr_primary002_0.geometry}
                        material={materials["primary.002"]}
                      />
                      <group name="door_rr_ok">
                        <mesh
                          name="door_rr_ok_primary002_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.door_rr_ok_primary002_0.geometry}
                          material={materials["primary.002"]}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="windscreen_dummy" position={[0, 0.729, 0.573]}>
                    <group name="windscreen_ok">
                      <mesh
                        name="windscreen_ok_glass0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.windscreen_ok_glass0_0.geometry}
                        material={materials["glass.0"]}
                      />
                    </group>
                  </group>
                  <group
                    name="bump_front_dummy"
                    position={[0.873, 1.931, 0.128]}
                  >
                    <group name="front_black">
                      <mesh
                        name="front_black_front_black0_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.front_black_front_black0_0.geometry}
                        material={materials["front_black.0"]}
                      />
                      <group name="chrome002">
                        <mesh
                          name="chrome002_back_chrome_light0_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.chrome002_back_chrome_light0_0.geometry
                          }
                          material={materials["back_chrome_light.0"]}
                        />
                      </group>
                      <group name="foglights_r">
                        <mesh
                          name="foglights_r_foglight_r_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.foglights_r_foglight_r_0.geometry}
                          material={materials.foglight_r}
                        />
                      </group>
                      <group name="foglights_l">
                        <mesh
                          name="foglights_l_foglight_l_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.foglights_l_foglight_l_0.geometry}
                          material={materials.foglight_l}
                        />
                      </group>
                      <group name="indicator_lights_r">
                        <mesh
                          name="indicator_lights_r_indicator_rf_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.indicator_lights_r_indicator_rf_0.geometry
                          }
                          material={materials.indicator_rf}
                        />
                      </group>
                      <group name="indicator_lights_l">
                        <mesh
                          name="indicator_lights_l_indicator_lf_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.indicator_lights_l_indicator_lf_0.geometry
                          }
                          material={materials.indicator_lf}
                        />
                      </group>
                      <group name="tembus_depan_ok">
                        <mesh
                          name="tembus_depan_ok_tembus_red0_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.tembus_depan_ok_tembus_red0_0.geometry
                          }
                          material={materials["tembus_red.0"]}
                        />
                      </group>
                    </group>
                    <group name="front_bumper_ok">
                      <mesh
                        name="front_bumper_ok_primary_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.front_bumper_ok_primary_0.geometry}
                        material={materials.primary}
                      />
                    </group>
                  </group>
                  <group
                    name="bump_rear_dummy"
                    position={[0.873, -1.929, 0.281]}
                  >
                    <group name="rear_bumper">
                      <mesh
                        name="rear_bumper_movsteer_101_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.rear_bumper_movsteer_101_0.geometry}
                        material={materials["movsteer_1.0.1"]}
                      />
                      <group name="rear_bumper_ok">
                        <mesh
                          name="rear_bumper_ok_primary_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.rear_bumper_ok_primary_0.geometry}
                          material={materials.primary}
                        />
                      </group>
                      <group name="light_pantulan">
                        <mesh
                          name="light_pantulan_light_pantulan0_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.light_pantulan_light_pantulan0_0.geometry
                          }
                          material={materials["light_pantulan.0"]}
                        />
                      </group>
                      <group name="tembus_belakang">
                        <mesh
                          name="tembus_belakang_tembus_red0_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.tembus_belakang_tembus_red0_0.geometry
                          }
                          material={materials["tembus_red.0"]}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="bonnet_dummy" position={[0, 1.326, 0.237]}>
                    <group name="bonnet_ok">
                      <mesh
                        name="bonnet_ok_primary_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.bonnet_ok_primary_0.geometry}
                        material={materials.primary}
                      />
                      <group name="chrome_bonnet_ok">
                        <mesh
                          name="chrome_bonnet_ok_movsteer_101_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.chrome_bonnet_ok_movsteer_101_0.geometry
                          }
                          material={materials["movsteer_1.0.1"]}
                        />
                      </group>
                    </group>
                  </group>
                </group>
                <group name="wheel_rf_dummy" position={[0.925, 1.757, -0.372]}>
                  <group name="wheels" ref={frontWheelsRef}>
                    <mesh
                      name="wheels_wheels2_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.wheels_wheels2_0.geometry}
                      material={materials["wheels.2"]}
                    />
                    <mesh
                      name="wheels_wheels0_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.wheels_wheels0_0.geometry}
                      material={materials["wheels.0"]}
                    />
                    <mesh
                      name="wheels_wheels1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.wheels_wheels1_0.geometry}
                      material={materials["wheels.1"]}
                    />
                    <mesh
                      name="wheels_movsteer_101_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.wheels_movsteer_101_0.geometry}
                      material={materials["movsteer_1.0.1"]}
                    />
                    <mesh
                      name="wheels_wheels3_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.wheels_wheels3_0.geometry}
                      material={materials["wheels.3"]}
                    />
                    <mesh
                      name="wheels_wheels4_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.wheels_wheels4_0.geometry}
                      material={materials["wheels.4"]}
                    />
                    <mesh
                      name="wheels_wheels6_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.wheels_wheels6_0.geometry}
                      material={materials["wheels.6"]}
                    />
                  </group>
                  <group
                    name="wheels001"
                    position={[0, -3.204, 0]}
                    scale={1.018}
                    ref={rearWheelsRef}
                  >
                    <mesh
                      name="wheels001_wheels2_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.wheels001_wheels2_0.geometry}
                      material={materials["wheels.2"]}
                    />
                    <mesh
                      name="wheels001_wheels0_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.wheels001_wheels0_0.geometry}
                      material={materials["wheels.0"]}
                    />
                    <mesh
                      name="wheels001_wheels1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.wheels001_wheels1_0.geometry}
                      material={materials["wheels.1"]}
                    />
                    <mesh
                      name="wheels001_movsteer_101_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.wheels001_movsteer_101_0.geometry}
                      material={materials["movsteer_1.0.1"]}
                    />
                    <mesh
                      name="wheels001_wheels3_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.wheels001_wheels3_0.geometry}
                      material={materials["wheels.3"]}
                    />
                    <mesh
                      name="wheels001_wheels4_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.wheels001_wheels4_0.geometry}
                      material={materials["wheels.4"]}
                    />
                    <mesh
                      name="wheels001_wheels6_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.wheels001_wheels6_0.geometry}
                      material={materials["wheels.6"]}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/tesla_2018_model_3.glb");
