/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_3: THREE.Mesh;
  };
  materials: {
    car_jeep_ren: THREE.MeshBasicMaterial;
  };
};

export function ModelSuv(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/suv2.glb") as GLTFResult;

  // 偏移量，使后轴在模型的几何中心上
  const rearAxleOffset = -3.555; // 将车体向前移动 3.555 米，使后轴对齐原点

  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Object_3"
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.car_jeep_ren}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.959, 1.067, 0.876]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/suv2.glb");
