/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    SUV_Body_Body_0: THREE.Mesh;
    SUV_Body_Glass_0: THREE.Mesh;
    SUV_Body_Optics_0: THREE.Mesh;
    Wheel_E_Body_0: THREE.Mesh;
    Wheel_E_Wheel_0001: THREE.Mesh;
    Wheel_E001_Body_0: THREE.Mesh;
    Wheel_E001_Wheel_0001: THREE.Mesh;
    Wheel_E002_Body_0: THREE.Mesh;
    Wheel_E002_Wheel_0001: THREE.Mesh;
    Wheel_E003_Wheel_0001: THREE.Mesh;
  };
  materials: {
    ["Body_7.001"]: THREE.MeshStandardMaterial;
    Glass_7: THREE.MeshStandardMaterial;
    Optics_7: THREE.MeshStandardMaterial;
    Body_7: THREE.MeshStandardMaterial;
    Wheel_6: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/suv2.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group
          name="SUV_Body"
          position={[-0.129, 0.134, -4.722]}
          rotation={[-Math.PI / 2, 0, -1.257]}
          scale={0.001}
        >
          <mesh
            name="SUV_Body_Body_0"
            castShadow
            receiveShadow
            geometry={nodes.SUV_Body_Body_0.geometry}
            material={materials["Body_7.001"]}
          />
          <mesh
            name="SUV_Body_Glass_0"
            castShadow
            receiveShadow
            geometry={nodes.SUV_Body_Glass_0.geometry}
            material={materials.Glass_7}
          />
          <mesh
            name="SUV_Body_Optics_0"
            castShadow
            receiveShadow
            geometry={nodes.SUV_Body_Optics_0.geometry}
            material={materials.Optics_7}
          />
        </group>
        <group
          name="Wheel_E001"
          position={[-1.296, 0.507, -3.582]}
          rotation={[-Math.PI / 2, 0, -1.257]}
          scale={0.001}
        >
          <mesh
            name="Wheel_E_Body_0"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_E_Body_0.geometry}
            material={materials.Body_7}
          />
          <mesh
            name="Wheel_E_Wheel_0001"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_E_Wheel_0001.geometry}
            material={materials.Wheel_6}
          />
        </group>
        <group
          name="Wheel_E001001"
          position={[1.301, 0.507, -4.426]}
          rotation={[-Math.PI / 2, 0, -1.257]}
          scale={0.001}
        >
          <mesh
            name="Wheel_E001_Body_0"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_E001_Body_0.geometry}
            material={materials.Body_7}
          />
          <mesh
            name="Wheel_E001_Wheel_0001"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_E001_Wheel_0001.geometry}
            material={materials.Wheel_6}
          />
        </group>
        <group
          name="Wheel_E002001"
          position={[-1.743, 0.507, -4.959]}
          rotation={[-Math.PI / 2, 0, -1.257]}
          scale={0.001}
        >
          <mesh
            name="Wheel_E002_Body_0"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_E002_Body_0.geometry}
            material={materials.Body_7}
            position={[0.001, 0, 0]}
          />
          <mesh
            name="Wheel_E002_Wheel_0001"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_E002_Wheel_0001.geometry}
            material={materials.Wheel_6}
            position={[0.001, 0, 0]}
          />
        </group>
        <mesh
          name="Wheel_E003_Wheel_0001"
          castShadow
          receiveShadow
          geometry={nodes.Wheel_E003_Wheel_0001.geometry}
          material={materials.Wheel_6}
          position={[0.854, 0.507, -5.803]}
          rotation={[-Math.PI / 2, 0, -1.257]}
          scale={0.001}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/suv2.glb");
