/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Jose Bronze (https://sketchfab.com/pinceladas3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/jeep-renegade-2016-192f7e81dce84c6780434f692a0f96c5
Title: Jeep Renegade 2016
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
  };
  materials: {
    FrontColor: THREE.MeshBasicMaterial;
    car_jeep_ren: THREE.MeshBasicMaterial;
  };
};

export function ModelSuv(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/jeep.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene" scale={0.8}>
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Jeep_Renegade_2016objcleanermaterialmergergles">
            <mesh
              name="Object_2"
              castShadow
              receiveShadow
              geometry={nodes.Object_2.geometry}
              material={materials.FrontColor}
            />
            <mesh
              name="Object_3"
              castShadow
              receiveShadow
              geometry={nodes.Object_3.geometry}
              material={materials.car_jeep_ren}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/jeep.glb");
