/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    BaseMeshBKP: THREE.SkinnedMesh;
    mixamorigHips: THREE.Bone;
  };
  materials: {};
};

type ActionName = "Armature|mixamo.com|Layer0";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function WalkModel(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF("/walk.glb") as GLTFResult;
  const { actions } = useAnimations<THREE.AnimationClip>(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <skinnedMesh
            name="BaseMeshBKP"
            geometry={nodes.BaseMeshBKP.geometry}
            material={nodes.BaseMeshBKP.material}
            skeleton={nodes.BaseMeshBKP.skeleton}
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/walk.glb");
